### ISSUE TITLE
Support multiple composer versions

### ISSUE THREAD

**Issue by viceice** [renovatebot/docker-composer#27]
Since version 1.10.0 composer writes the version to the lockfile, so we can use it to select the corresponding composer release.

see #26 

*Tasks*
- [x] switch to release from github actions
- [x] build multiple docker images from specific composer versions (1.9.x, 1.10.x)
- [ ] add renovate rules, to update the max version and patch releases

**Comment by rarkins** [comment]
Secrets added:
![image](https://user-images.githubusercontent.com/6311784/76739542-9f011a80-676c-11ea-8e8e-b21708cb93b0.png)
