### ISSUE TITLE
Reason for this image

### ISSUE THREAD

**Issue by arxeiss** [renovatebot/docker-composer#47]
I wanted to use Renovate only for PHP/Composer updates, so I cannot use `renovate:slim`. I found this repo as well and related image. But that image is missing `renovate` command. What is the purpose of this image?

**Comment by viceice** [comment]
This image is uses by the slim renovate, which will run all external tools as docker side container.

Why do you can't use the slim renovate image?

If you need help to run renovate you can open an issue in our config-help repo.
